W0206 08:33:02.384332       1 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "testing-webonly-helm-chart-415-w9xsc2o5wy-server-test" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "testing-webonly-helm-chart-415-w9xsc2o5wy-server-test" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "testing-webonly-helm-chart-415-w9xsc2o5wy-server-test" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "testing-webonly-helm-chart-415-w9xsc2o5wy-server-test" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.2
        profile:
            VendorType: partner
            version: v1.2
        reportDigest: uint64:2067395052393676851
        chart-uri: N/A
        digests:
            chart: sha256:101c639ce203af13e2a4899d78e1d23d2f0829e8299fa15687cae83c782c7a98
            package: b0a24a914e757e40ffbe766d1f2879d609310527d1e2089e341d356e47e69797
        lastCertifiedTimestamp: "2024-02-06T08:33:17.711185+00:00"
        testedOpenShiftVersion: "4.15"
        supportedOpenShiftVersions: '>=4.14'
        webCatalogOnly: true
    chart:
        name: testing-webonly-helm-chart-415
        home: https://www.vaultproject.io
        sources:
            - https://github.com/hashicorp/vault
            - https://github.com/hashicorp/vault-helm
            - https://github.com/hashicorp/vault-k8s
            - https://github.com/hashicorp/vault-csi-provider
        version: 0.0.3
        description: Official HashiCorp Vault Chart
        keywords:
            - vault
            - security
            - encryption
            - secrets
            - management
            - automation
            - infrastructure
        maintainers: []
        icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.15.2
        deprecated: false
        annotations:
            charts.openshift.io/name: testing-webonly-helm-chart-415
        kubeversion: '>= 1.27.0-0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault-k8s:1.3.1-ubi
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault:1.15.2-ubi
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist

