apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.12.0
        profile:
            VendorType: partner
            version: v1.2
        reportDigest: uint64:12647420089069634616
        chart-uri: N/A
        digests:
            chart: sha256:68330382e0e041b3c303a119250202c7b416695c0bc518e4dbe4782374367fd3
            package: f84c60bc355ccb571070623e7cfe0f4a1300d74cdb26283e2c86f36ba07b6f9b
        lastCertifiedTimestamp: "2023-06-25T17:03:47.833535+00:00"
        testedOpenShiftVersion: "4.13"
        supportedOpenShiftVersions: '>=4.3'
        webCatalogOnly: true
    chart:
        name: helm-chart-ocp413
        home: https://www.vaultproject.io
        sources:
            - https://github.com/hashicorp/vault
            - https://github.com/hashicorp/vault-helm
            - https://github.com/hashicorp/vault-k8s
            - https://github.com/hashicorp/vault-csi-provider
        version: 0.21.45
        description: Official HashiCorp Vault Chart
        keywords:
            - vault
            - security
            - encryption
            - secrets
            - management
            - automation
            - infrastructure
        maintainers: []
        icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.11.2
        deprecated: false
        annotations:
            charts.openshift.io/name: helm-chart-ocp413
        kubeversion: '>= 1.16.0-0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault-k8s:0.17.0-ubi
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault:1.11.2-ubi
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs

