W0504 07:13:53.851944       1 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "sidecar-injector" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "sidecar-injector" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "sidecar-injector" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "sidecar-injector" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0504 07:13:53.938791       1 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "vault" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "vault" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "vault" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "vault" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0504 07:14:36.385739       1 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "webonly-helm-chart-34ajuulsva-server-test" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "webonly-helm-chart-34ajuulsva-server-test" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webonly-helm-chart-34ajuulsva-server-test" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webonly-helm-chart-34ajuulsva-server-test" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.10.1
        profile:
            VendorType: partner
            version: v1.2
        reportDigest: uint64:2414480072003157901
        chart-uri: N/A
        digests:
            chart: sha256:e520d6c00899517daa32753ccb4d4884d39d526039fd75e1b69801da9e29203c
            package: 0d572cae05fb97d87613587df0e585e8f61c0792811b9c2a8ca54f470cef7bf8
        lastCertifiedTimestamp: "2023-05-04T07:14:48.455598+00:00"
        testedOpenShiftVersion: "4.12"
        supportedOpenShiftVersions: '>=4.3'
        webCatalogOnly: true
    chart:
        name: webonly-helm-chart
        home: https://www.vaultproject.io
        sources:
            - https://github.com/hashicorp/vault
            - https://github.com/hashicorp/vault-helm
            - https://github.com/hashicorp/vault-k8s
            - https://github.com/hashicorp/vault-csi-provider
        version: 0.21.0
        description: Official HashiCorp Vault Chart
        keywords:
            - vault
            - security
            - encryption
            - secrets
            - management
            - automation
            - infrastructure
        maintainers: []
        icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.11.2
        deprecated: false
        annotations:
            charts.openshift.io/name: webonly-helm-chart
        kubeversion: '>= 1.16.0-0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault-k8s:0.17.0-ubi
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault:1.11.2-ubi
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs

