apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.2
        profile:
            VendorType: partner
            version: v1.2
        reportDigest: uint64:1361959353566772357
        chart-uri: N/A
        digests:
            chart: sha256:9a7359e9cfa4bc75c1279a6325bb41f4b9835253d0b0c78c338ddaa0855ed522
            package: 58dfae4c0691b2f34165995addcd4d338d4d0387fbe7e8a829070f399227d269
        lastCertifiedTimestamp: "2024-02-08T12:42:50.717656+00:00"
        testedOpenShiftVersion: "4.14"
        supportedOpenShiftVersions: '>=4.14'
        webCatalogOnly: true
    chart:
        name: helm-chart-ocp413
        home: https://www.vaultproject.io
        sources:
            - https://github.com/hashicorp/vault
            - https://github.com/hashicorp/vault-helm
            - https://github.com/hashicorp/vault-k8s
            - https://github.com/hashicorp/vault-csi-provider
        version: 0.21.135
        description: Official HashiCorp Vault Chart
        keywords:
            - vault
            - security
            - encryption
            - secrets
            - management
            - automation
            - infrastructure
        maintainers: []
        icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.15.2
        deprecated: false
        annotations:
            charts.openshift.io/name: helm-chart-ocp413
        kubeversion: '>= 1.27.0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault-k8s:1.3.1-ubi
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault:1.15.2-ubi
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs

